### ISSUE TITLE
adding the attached ITALIAN dictionaries

### ISSUE THREAD

**Issue by nicoursi** [nulab/zxcvbn4j#131]
Hi,
I was wondering if the following dictionaries could be added:

[italian_wikipedia.txt](https://github.com/nulab/zxcvbn4j/files/10683822/italian_wikipedia.txt)
[italian_names.txt](https://github.com/nulab/zxcvbn4j/files/10683823/italian_names.txt)
[italian_surnames.txt](https://github.com/nulab/zxcvbn4j/files/10683824/italian_surnames.txt)

**Comment by AsfarHorani** [comment]
@nicoursi can u guide me a little more, I willing to contribute

**Comment by vvatanabe** [comment]
@nicoursi @AsfarHorani 

As for dictionaries, only English-speaking countries are supported by default due to the huge amount of data. You can use your own dictionaries in the following ways, so please try them out.
[Customize internal dictionaries and keyboards](https://github.com/nulab/zxcvbn4j#customize-internal-dictionaries-and-keyboards-1)
