### ISSUE TITLE
adding new spanish dictionary and surnames, es_ES

### ISSUE THREAD

**Issue by MiguelPalomo** [nulab/zxcvbn4j#134]
[messages_es.properties.txt](https://github.com/nulab/zxcvbn4j/files/10899827/messages_es.properties.txt)
[spanish surnames.txt](https://github.com/nulab/zxcvbn4j/files/10899828/spanish.surnames.txt)

**Comment by vvatanabe** [comment]
@MiguelPalomo 

The following PRs supported the Spanish message.
https://github.com/nulab/zxcvbn4j/pull/135

As for dictionaries, only English-speaking countries are supported by default due to the huge amount of data. You can use your own dictionaries in the following ways, so please try them out.
[Customize internal dictionaries and keyboards](https://github.com/nulab/zxcvbn4j#customize-internal-dictionaries-and-keyboards-1)
