### ISSUE TITLE
Discrepancy in password score between this version and the original package

### ISSUE THREAD

**Issue by TheAlexPorter** [nulab/zxcvbn4j#84]
Hi all,

I'm using `zxcvbn4j` on the backend and the original `zxcvbn` from dropbox on the front end. When I use the following example password, I get two different scores.

Password: `Sigma@123`

With `zxcvbn4j` I get 2, but with `zxcvbn` I get 3. If we use the [demo tool](https://lowe.github.io/tryzxcvbn/), we can see that 3 is the expected score.

Any thoughts on how we can get this library to match the original version's output?

**Comment by Stephen2** [comment]
Agree :+1: replicated using `1.3.0` and `1.3.4`

**Comment by vvatanabe** [comment]
I'll investigate.

**Comment by TheAlexPorter** [comment]
Hi all, any update on this? Where you able to replicate the issue @vvatanabe?

**Comment by vvatanabe** [comment]
@TheAlexPorter Yes, I able to replicate this issue.  But we're still investigating the cause.

**Comment by mrFloony** [comment]
@vvatanabe, I briefly compared the processing of zxcvbn4j and zxcvbn dropbox (demo tool in https://lowe.github.io/tryzxcvbn/)
In the demo tool, the password Sigma@123 is divided into "Sigma@" ('bruteforce') and "123" ('sequence').
In the zxcvbn4j, the password is divided into "Sigma" ('dictionary') and "@123" ('spatial').

Therefore, it is not known which result from the libraries will be considered correct, since 'bruteforce' is not very suitable for dropbox.

**Comment by Emi75** [comment]
We have the same issue in the latest version - https://github.com/dropbox/zxcvbn/issues/320
Any feedback on this issue or the project is not still mantained?
Thanks in advance.

**Comment by Stephen2** [comment]
Thank you @vvatanabe :)
