### ISSUE TITLE
Logging must not be done to stdout

### ISSUE THREAD

**Issue by mfriedenhagen** [nulab/zxcvbn4j#94]
I am referencing https://lgtm.com/projects/g/nulab/zxcvbn4j?mode=list here:
* While the reported error by LGTM is about arrays at https://lgtm.com/projects/g/nulab/zxcvbn4j/snapshot/c7e6d69b55a6c38bb1eaac458628fc5a07fc432c/files/src/main/java/com/nulabinc/zxcvbn/matchers/DateMatcher.java?sort=name&dir=ASC&mode=heatmap#L46, I think it is an anti-pattern for a library to `print` anything to `stdout` or `stderr`.
* I have not inspected the rest of the source, but all logging should be done to a proper logger.
* I would go for e.g. slf4j as facade here and log to debug. 
* If adding a dependency is not feasible, please just use the `java.util.logging` logger included in the JDK. There are wrappers for other libraries which redirect that one.

**Comment by vvatanabe** [comment]
@mfriedenhagen Thanks for good feed back! 

You're right, it's not a good pattern for a library to print directly.
We don't want to add as many dependencies as possible. So I prefer java.util.logging.

**Comment by oliverboehme** [comment]
So far those occurences of `System.out.println` are used in order to log `NumberFormatException`s.
I tried to write a Unit test in order to even reach those branches of code, which turned out very hard.

In my eyes it could be that those branches are only reached in case of programming error, so in this case I'd avoid catching the `NumberFormatException`s, and therefore also avoid using `System.out.println`.

If you are interested in a patch, have a look at this Diff:
https://github.com/nulab/zxcvbn4j/compare/master...oliverboehme:issue-94
:warning:  But beware it is not tested, and IMO also not testable at all.

**Comment by vvatanabe** [comment]
We removed `System.out.println`. Thanks!
